source 'https://rubygems.org'
gem 'rails', '3.2.8'
gem 'mysql2'
gem 'json'
gem 'therubyracer'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'thin'
gem 'capistrano'
gem 'rvm-capistrano'
gem 'rmagick'
gem 'haml'
gem 'sass'
gem 'sendgrid'
gem "paperclip"
gem 'foreigner'
gem 'will_paginate'
gem 'devise'
gem 'zip'
gem 'twitter'
gem 'omniauth-twitter'
gem 'simple-rss'
gem 'googl'
gem 'nokogiri'
gem 'hpricot'
gem 'sax-machine'
